// <auto-generated />
namespace ADServerDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Statisticsupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Statisticsupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201404300111072_Statistics-update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
